version: 2

jobs:
  - docker:
      image: golang:1.19.0-buster
    template:
      name: go
      skip:
        - test  # CI tests require a database

publications:
  - url: https://pkg.go.dev/github.com/launchdarkly/go-server-sdk-redis-go-redis
    description: documentation
