name: Build and Test
on:
  push:
    branches: ["main", "feat/**"]
    paths-ignore:
      - "**.md" # Don't run CI on markdown changes.
  pull_request:
    branches: ["main", "feat/**"]
    paths-ignore:
      - "**.md"

jobs:
  go-mod-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Go mod tidy
        run: |
          go mod tidy
          git diff --exit-code -- go.mod go.sum

  go-versions:
    uses: ./.github/workflows/go-versions.yml

  # Runs the common tasks (unit tests, lint, contract tests) for each Go version.
  test-linux:
    name: ${{ format('Linux, Go {0}', matrix.go-version) }}
    needs: go-versions
    strategy:
      # Let jobs fail independently, in case it's a single version that's broken.
      fail-fast: false
      matrix:
        go-version: ${{ fromJSON(needs.go-versions.outputs.matrix) }}
    uses: ./.github/workflows/common_ci.yml
    with:
      go-version: ${{ matrix.go-version }}

  test-linux-redis-cluster:
    name: ${{ format('Linux, Go {0} with Redis Cluster', matrix.go-version) }}
    runs-on: ubuntu-latest
    env:
      LD_TEST_REDIS_ADDRESSES: redis:6379 redis:6380 redis:6381
    needs: go-versions
    strategy:
      fail-fast: false
      matrix:
        go-version: ${{ fromJSON(needs.go-versions.outputs.matrix) }}
    services:
      redis-cluster:
        image: grokzen/redis-cluster@sha256:1a78d201c8913898b48933e431184d16b558f91ac538abd324c277518895bc87 # v7.2.5
        env:
          IP: 0.0.0.0
          INITIAL_PORT: 6379
          MASTERS: 3
          SLAVES_PER_MASTER: 0
        ports:
          - 6379:6379
          - 6380:6380
          - 6381:6381

    container:
      image: ubuntu:22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Deps
        run: |
          apt-get update
          apt-get install -y make curl gcc
      - uses: ./.github/actions/unit-tests
        with:
          upload-results: "false"

  test-windows:
    name: ${{ format('Windows, Go {0}', matrix.go-version) }}
    runs-on: windows-2022
    needs: go-versions
    strategy:
      fail-fast: false
      matrix:
        go-version: ${{ fromJSON(needs.go-versions.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install Redis
        shell: powershell
        # The process needs to be started with Start-Process, which creates a new process independent
        # of this shell. That way it can run in the background when we move on to the Go test step.
        run: |
          choco install redis
          Start-Process redis-server

      - name: Test
        run: go test -count=1 -race ./...
